#If enabled will output to the debug.log when a structure is disabled.
"Enable Debug" = false
#This list defines the structures that should be disabled from generating.
"Disabled Structures" = ["minecraft:mansion", "minecraft:village_desert", "minecraft:village_plains", "minecraft:village_savanna", "minecraft:village_snowy", "minecraft:village_taiga"]

